<a href="https://colab.research.google.com/github/vaishnavi-gujare/Countries-Dataframe/blob/main/game_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving battles.csv to battles.csv

In [4]:
filepath = '/content/battles.csv'
df = pd.read_csv(filepath)

In [5]:
df

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,...,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN
2,Battle of Riverrun,298,3,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,1.0,15000.0,10000.0,"Jaime Lannister, Andros Brax","Edmure Tully, Tytos Blackwood",1.0,Riverrun,The Riverlands,NaN
3,Battle of the Green Fork,298,4,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,1.0,18000.0,20000.0,"Roose Bolton, Wylis Manderly, Medger Cerwyn, H...","Tywin Lannister, Gregor Clegane, Kevan Lannist...",1.0,Green Fork,The Riverlands,NaN
4,Battle of the Whispering Wood,298,5,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,1875.0,6000.0,"Robb Stark, Brynden Tully",Jaime Lannister,1.0,Whispering Wood,The Riverlands,NaN
5,Battle of the Camps,298,6,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,0.0,0.0,6000.0,12625.0,"Robb Stark, Tytos Blackwood, Brynden Tully","Lord Andros Brax, Forley Prester",1.0,Riverrun,The Riverlands,NaN
6,Sack of Darry,298,7,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Darry,...,0.0,0.0,NaN,NaN,Gregor Clegane,Lyman Darry,1.0,Darry,The Riverlands,NaN
7,Battle of Moat Cailin,299,8,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,0.0,NaN,NaN,Victarion Greyjoy,NaN,1.0,Moat Cailin,The North,NaN
8,Battle of Deepwood Motte,299,9,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,0.0,1000.0,NaN,Asha Greyjoy,NaN,1.0,Deepwood Motte,The North,NaN
9,Battle of the Stony Shore,299,10,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,0.0,264.0,NaN,Theon Greyjoy,NaN,1.0,Stony Shore,The North,Greyjoy's troop number based on the Battle of ...
10,Battle of Torrhen's Square,299,11,Robb Stark,Balon/Euron Greyjoy,Stark,NaN,NaN,NaN,Greyjoy,...,0.0,0.0,244.0,900.0,"Rodrik Cassel, Cley Cerwyn",Dagmer Cleftjaw,1.0,Torrhen's Square,The North,Greyjoy's troop number comes from the 264 esti...
11,Battle of Winterfell,299,12,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,1.0,20.0,NaN,Theon Greyjoy,Bran Stark,1.0,Winterfell,The North,It isn't mentioned how many Stark men are left...
12,Sack of Torrhen's Square,299,13,Balon/Euron Greyjoy,Balon/Euron Greyjoy,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,1.0,NaN,NaN,Dagmer Cleftjaw,NaN,1.0,Torrhen's Square,The North,NaN
13,Sack of Winterfell,299,14,Joffrey/Tommen Baratheon,Robb Stark,Bolton,Greyjoy,NaN,NaN,Stark,...,1.0,0.0,618.0,2000.0,"Ramsay Snow, Theon Greyjoy","Rodrik Cassel, Cley Cerwyn, Leobald Tallhart",1.0,Winterfell,The North,Since House Bolton betrays the Starks for Hous...
14,Battle of Oxcross,299,15,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,6000.0,10000.0,"Robb Stark, Brynden Tully","Stafford Lannister, Roland Crakehall, Antario ...",1.0,Oxcross,The Westerlands,NaN
15,Siege of Storm's End,299,16,Stannis Baratheon,Renly Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,1.0,0.0,5000.0,20000.0,"Stannis Baratheon, Davos Seaworth","Renly Baratheon, Cortnay Penrose, Loras Tyrell...",1.0,Storm's End,The Stormlands,NaN
16,Battle of the Fords,299,17,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,0.0,20000.0,10000.0,"Tywin Lannister, Flement Brax, Gregor Clegane,...","Edmure Tully, Jason Mallister, Karyl Vance",1.0,Red Fork,The Riverlands,NaN
17,Sack of Harrenhal,299,18,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,0.0,100.0,100.0,"Roose Bolton, Vargo Hoat, Robett Glover",Amory Lorch,1.0,Harrenhal,The Riverlands,NaN
18,Battle of the Crag,299,19,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,0.0,0.0,6000.0,NaN,"Robb Stark, Smalljon Umber, Black Walder Frey",Rolph Spicer,1.0,Crag,The Westerlands,NaN
19,Battle of the Blackwater,299,20,Stannis Baratheon,Joffrey/Tommen Baratheon,Baratheon,NaN,NaN,NaN,Lannister,...,1.0,1.0,21000.0,7250.0,"Stannis Baratheon, Imry Florent, Guyard Morrig...","Tyrion Lannister, Jacelyn Bywater, Sandor Cleg...",1.0,King's Landing,The Crownlands,NaN
20,Siege of Darry,299,21,Robb Stark,Joffrey/Tommen Baratheon,Darry,NaN,NaN,NaN,Lannister,...,0.0,0.0,NaN,NaN,Helman Tallhart,NaN,1.0,Darry,The Riverlands,NaN
21,Battle of Duskendale,299,22,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,0.0,3000.0,NaN,"Robertt Glover, Helman Tallhart","Randyll Tarly, Gregor Clegane",1.0,Duskendale,The Crownlands,NaN
22,Battle of the Burning Septry,299,23,NaN,NaN,Brotherhood without Banners,NaN,NaN,NaN,Brave Companions,...,0.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,The Riverlands,NaN
23,Battle of the Ruby Ford,299,24,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Stark,...,0.0,0.0,NaN,6000.0,Gregor Clegane,"Roose Bolton, Wylis Manderly",NaN,Ruby Ford,The Riverlands,NaN
24,Retaking of Harrenhal,299,25,Joffrey/Tommen Baratheon,NaN,Lannister,NaN,NaN,NaN,Brave Companions,...,1.0,0.0,NaN,NaN,Gregor Clegane,Vargo Hoat,1.0,Harrenhal,The Riverlands,NaN
25,The Red Wedding,299,26,Joffrey/Tommen Baratheon,Robb Stark,Frey,Bolton,NaN,NaN,Stark,...,1.0,1.0,3500.0,3500.0,"Walder Frey, Roose Bolton, Walder Rivers",Robb Stark,1.0,The Twins,The Riverlands,This observation refers to the battle against ...
26,Siege of Seagard,299,27,Robb Stark,Joffrey/Tommen Baratheon,Frey,NaN,NaN,NaN,Mallister,...,0.0,1.0,NaN,NaN,Walder Frey,Jason Mallister,1.0,Seagard,The Riverlands,NaN
27,Battle of Castle Black,300,28,Stannis Baratheon,Mance Rayder,Free folk,Thenns,Giants,NaN,Night's Watch,...,1.0,1.0,100000.0,1240.0,"Mance Rayder, Tormund Giantsbane, Harma Dogshe...","Stannis Baratheon, Jon Snow, Donal Noye, Cotte...",0.0,Castle Black,Beyond the Wall,NaN
28,Fall of Moat Cailin,300,29,Joffrey/Tommen Baratheon,Balon/Euron Greyjoy,Bolton,NaN,NaN,NaN,Greyjoy,...,0.0,0.0,NaN,NaN,Ramsey Bolton,NaN,0.0,Moat Cailin,The North,NaN
29,Sack of Saltpans,300,30,NaN,NaN,Brave Companions,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,Rorge,NaN,0.0,Saltpans,The Riverlands,NaN
30,Retaking of Deepwood Motte,300,31,Stannis Baratheon,Balon/Euron Greyjoy,Baratheon,Karstark,Mormont,Glover,Greyjoy,...,0.0,0.0,4500.0,200.0,"Stannis Baratheon, Alysane Mormot",Asha Greyjoy,0.0,Deepwood Motte,The North,NaN
31,Battle of the Shield Islands,300,32,Balon/Euron Greyjoy,Joffrey/Tommen Baratheon,Greyjoy,NaN,NaN,NaN,Tyrell,...,0.0,0.0,NaN,NaN,"Euron Greyjoy, Victarion Greyjoy",NaN,0.0,Shield Islands,The Reach,NaN
32,"Invasion of Ryamsport, Vinetown, and Starfish ...",300,33,Balon/Euron Greyjoy,Joffrey/Tommen Baratheon,Greyjoy,NaN,NaN,NaN,Tyrell,...,0.0,0.0,NaN,NaN,"Euron Greyjoy, Victarion Greyjoy",NaN,0.0,"Ryamsport, Vinetown, Starfish Harbor",The Reach,NaN
33,Second Seige of Storm's End,300,34,Joffrey/Tommen Baratheon,Stannis Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,0.0,0.0,NaN,200.0,"Mace Tyrell, Mathis Rowan",Gilbert Farring,0.0,Storm's End,The Stormlands,NaN
34,Siege of Dragonstone,300,35,Joffrey/Tommen Baratheon,Stannis Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,0.0,0.0,2000.0,NaN,"Loras Tyrell, Raxter Redwyne",Rolland Storm,0.0,Dragonstone,The Stormlands,NaN
35,Siege of Riverrun,300,36,Joffrey/Tommen Baratheon,Robb Stark,Lannister,Frey,NaN,NaN,Tully,...,0.0,0.0,3000.0,NaN,"Daven Lannister, Ryman Fey, Jaime Lannister",Brynden Tully,0.0,Riverrun,The Riverlands,NaN
36,Siege of Raventree,300,37,Joffrey/Tommen Baratheon,Robb Stark,Bracken,Lannister,NaN,NaN,Blackwood,...,0.0,1.0,1500.0,NaN,"Jonos Bracken, Jaime Lannister",Tytos Blackwood,0.0,Raventree,The Riverlands,NaN
37,Siege of Winterfell,300,38,Stannis Baratheon,Joffrey/Tommen Baratheon,Baratheon,Karstark,Mormont,Glover,Bolton,...,NaN,NaN,5000.0,8000.0,Stannis Baratheon,Roose Bolton,0.0,Winterfell,The North,NaN

In [6]:
df.head()

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,...,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN
2,Battle of Riverrun,298,3,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,1.0,15000.0,10000.0,"Jaime Lannister, Andros Brax","Edmure Tully, Tytos Blackwood",1.0,Riverrun,The Riverlands,NaN
3,Battle of the Green Fork,298,4,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,1.0,18000.0,20000.0,"Roose Bolton, Wylis Manderly, Medger Cerwyn, H...","Tywin Lannister, Gregor Clegane, Kevan Lannist...",1.0,Green Fork,The Riverlands,NaN
4,Battle of the Whispering Wood,298,5,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,1875.0,6000.0,"Robb Stark, Brynden Tully",Jaime Lannister,1.0,Whispering Wood,The Riverlands,NaN

In [7]:
df.tail()

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
33,Second Seige of Storm's End,300,34,Joffrey/Tommen Baratheon,Stannis Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,0.0,0.0,NaN,200.0,"Mace Tyrell, Mathis Rowan",Gilbert Farring,0.0,Storm's End,The Stormlands,NaN
34,Siege of Dragonstone,300,35,Joffrey/Tommen Baratheon,Stannis Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,0.0,0.0,2000.0,NaN,"Loras Tyrell, Raxter Redwyne",Rolland Storm,0.0,Dragonstone,The Stormlands,NaN
35,Siege of Riverrun,300,36,Joffrey/Tommen Baratheon,Robb Stark,Lannister,Frey,NaN,NaN,Tully,...,0.0,0.0,3000.0,NaN,"Daven Lannister, Ryman Fey, Jaime Lannister",Brynden Tully,0.0,Riverrun,The Riverlands,NaN
36,Siege of Raventree,300,37,Joffrey/Tommen Baratheon,Robb Stark,Bracken,Lannister,NaN,NaN,Blackwood,...,0.0,1.0,1500.0,NaN,"Jonos Bracken, Jaime Lannister",Tytos Blackwood,0.0,Raventree,The Riverlands,NaN
37,Siege of Winterfell,300,38,Stannis Baratheon,Joffrey/Tommen Baratheon,Baratheon,Karstark,Mormont,Glover,Bolton,...,NaN,NaN,5000.0,8000.0,Stannis Baratheon,Roose Bolton,0.0,Winterfell,The North,NaN

In [8]:
df.shape

(38, 25)

In [9]:
df.columns

Index(['name', 'year', 'battle_number', 'attacker_king', 'defender_king',
       'attacker_1', 'attacker_2', 'attacker_3', 'attacker_4', 'defender_1',
       'defender_2', 'defender_3', 'defender_4', 'attacker_outcome',
       'battle_type', 'major_death', 'major_capture', 'attacker_size',
       'defender_size', 'attacker_commander', 'defender_commander', 'summer',
       'location', 'region', 'note'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                38 non-null     object
 1   year                38 non-null     int64
 2   battle_number       38 non-null     int64
 3   attacker_king       36 non-null     object
 4   defender_king       35 non-null     object
 5   attacker_1          38 non-null     object
 6   attacker_2          10 non-null     object
 7   attacker_3          3 non-null      object
 8   attacker_4          2 non-null      object
 9   defender_1          37 non-null     object
 10  defender_2          2 non-null      object
 11  defender_3          0 non-null      float64
 12  defender_4          0 non-null      float64
 13  attacker_outcome    37 non-null     object
 14  battle_type         37 non-null     object
 15  major_death         37 non-null     float64
 16  major_capture       37 non-null     float64
 17  attacker_size       24 non-null     float64
 18  defender_size       19 non-null     float64
 19  attacker_commander  37 non-null     object
 20  defender_commander  28 non-null     object
 21  summer              37 non-null     float64
 22  location            37 non-null     object
 23  region              38 non-null     object
 24  note                5 non-null      object
dtypes: float64(7), int64(2), object(16)
memory usage: 7.6+ KB

In [11]:
df.describe()

,year,battle_number,defender_3,defender_4,major_death,major_capture,attacker_size,defender_size,summer
count,38.000000,38.000000,0.0,0.0,37.000000,37.000000,24.000000,19.000000,37.000000
mean,299.105263,19.500000,NaN,NaN,0.351351,0.297297,9942.541667,6428.157895,0.702703
std,0.689280,11.113055,NaN,NaN,0.483978,0.463373,20283.092065,6225.182106,0.463373
min,298.000000,1.000000,NaN,NaN,0.000000,0.000000,20.000000,100.000000,0.000000
25%,299.000000,10.250000,NaN,NaN,0.000000,0.000000,1375.000000,1070.000000,0.000000
50%,299.000000,19.500000,NaN,NaN,0.000000,0.000000,4000.000000,6000.000000,1.000000
75%,300.000000,28.750000,NaN,NaN,1.000000,1.000000,8250.000000,10000.000000,1.000000
max,300.000000,38.000000,NaN,NaN,1.000000,1.000000,100000.000000,20000.000000,1.000000

In [12]:
df.dtypes

name                   object
year                    int64
battle_number           int64
attacker_king          object
defender_king          object
attacker_1             object
attacker_2             object
attacker_3             object
attacker_4             object
defender_1             object
defender_2             object
defender_3            float64
defender_4            float64
attacker_outcome       object
battle_type            object
major_death           float64
major_capture         float64
attacker_size         float64
defender_size         float64
attacker_commander     object
defender_commander     object
summer                float64
location               object
region                 object
note                   object
dtype: object

In [13]:
df.isnull().sum()

name                   0
year                   0
battle_number          0
attacker_king          2
defender_king          3
attacker_1             0
attacker_2            28
attacker_3            35
attacker_4            36
defender_1             1
defender_2            36
defender_3            38
defender_4            38
attacker_outcome       1
battle_type            1
major_death            1
major_capture          1
attacker_size         14
defender_size         19
attacker_commander     1
defender_commander    10
summer                 1
location               1
region                 0
note                  33
dtype: int64

In [14]:
df.nunique()

name                  38
year                   3
battle_number         38
attacker_king          4
defender_king          6
attacker_1            11
attacker_2             7
attacker_3             2
attacker_4             1
defender_1            12
defender_2             2
defender_3             0
defender_4             0
attacker_outcome       2
battle_type            4
major_death            2
major_capture          2
attacker_size         19
defender_size         14
attacker_commander    31
defender_commander    28
summer                 2
location              27
region                 7
note                   5
dtype: int64

In [15]:
df.sample(5)

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
20,Siege of Darry,299,21,Robb Stark,Joffrey/Tommen Baratheon,Darry,NaN,NaN,NaN,Lannister,...,0.0,0.0,NaN,NaN,Helman Tallhart,NaN,1.0,Darry,The Riverlands,NaN
11,Battle of Winterfell,299,12,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,1.0,20.0,NaN,Theon Greyjoy,Bran Stark,1.0,Winterfell,The North,It isn't mentioned how many Stark men are left...
34,Siege of Dragonstone,300,35,Joffrey/Tommen Baratheon,Stannis Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,0.0,0.0,2000.0,NaN,"Loras Tyrell, Raxter Redwyne",Rolland Storm,0.0,Dragonstone,The Stormlands,NaN
9,Battle of the Stony Shore,299,10,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,0.0,264.0,NaN,Theon Greyjoy,NaN,1.0,Stony Shore,The North,Greyjoy's troop number based on the Battle of ...
19,Battle of the Blackwater,299,20,Stannis Baratheon,Joffrey/Tommen Baratheon,Baratheon,NaN,NaN,NaN,Lannister,...,1.0,1.0,21000.0,7250.0,"Stannis Baratheon, Imry Florent, Guyard Morrig...","Tyrion Lannister, Jacelyn Bywater, Sandor Cleg...",1.0,King's Landing,The Crownlands,NaN

In [16]:
df.value_counts()

Series([], Name: count, dtype: int64)